### ISSUE TITLE
Can we make Components colorless?

### ISSUE THREAD

**Issue by taras** [thefrontside/revolution#2]
While working on https://github.com/thefrontside/effection/pull/887, I found that using context in a nested child component required wrapping every parent component in an operation. This sucks because it's effectively making them colourful analogous to how using async in a sync function requires making the sync function async. 

It would be much better if we could stick to one or the other. What can we do to avoid having to turn parents into operations? Can we just use operations everywhere?

**Comment by cowboyd** [comment]
It's really up to the users of revolution and how they decide to use them. A route is just an operation that produces a `JSX.Element` how it does that is completely up to the thing producing the JSX.Element, and so it should be a decision in the Effection repo.

It really boils down to this. If we want to use context in your html functions, then they should all be operations, or if we want to separate them. It's really the same question about any value, not just a JSX value though. 

Let's experiment with both approaches in the Effection website, and then we can make recommendations based on that here.
